TYPO3:
  Flow:
    http:
      chain:
        'postprocess':
          chain:
            'custom':
              component: 'RoboticBrain\FlowContextHeader\HttpHeaderComponent'
              componentOptions:
                'headerName': 'X-ACTUAL_FLOW_CONTEXT'